services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "soundclown-postgres"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - $HOME/srv/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    restart: unless-stopped

  app:
      build: 
        context: .
        dockerfile: Dockerfile
      image: "soundclown-app"
      container_name: ${APP_CONTAINER_NAME}
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      depends_on:
        - postgres 
