version: '3'
services:
  db:
    image: soundclownacr.azurecr.io/db
    build: db
    volumes:
    - $HOME/srv/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    expose:
    - 5432:5432
    ports:
    - 5432:5432
    restart: always
  app:
    build: server/soundclownjpa
    image: soundclownacr.azurecr.io/app
    container_name: app
    expose:
    - 8080:8080
    ports:
    - 8080:8080
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    depends_on:
    - db
  ui: 
    build: client/soundclownui
    image: soundclownacr.azurecr.io/ui
    container_name: ui
    ports:
    - 80:80
    depends_on:
    - app
