services:
  db:
    image: postgres
    volumes:
    - $HOME/srv/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    expose:
    - 5432:5432
    ports:
    - 5432:5432
    restart: always
  app:
    build: server/soundclownjpa
    expose:
    - 8080:8080
    ports:
    - 8080:8080
    - 5005:5005 # for debugging
    volumes:
      - ./audio_files:/tmp/audio_files
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    depends_on:
    - db
  ui: 
    build: client/soundclownui
    ports:
    - 3000:3000
    depends_on:
    - app

